/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExperienceGalleryRouteImport } from './routes/experience-gallery'
import { Route as CalendarEventsRouteImport } from './routes/calendar-events'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as CheckoutRouteImport } from './routes/_checkout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyPaymentIdRouteImport } from './routes/verify.$paymentId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AuthenticatedTicketSalesRouteImport } from './routes/_authenticated/ticket-sales'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedItemsRouteImport } from './routes/_authenticated/items'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CheckoutCheckoutIndexRouteImport } from './routes/_checkout/checkout/index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as CheckoutCheckoutSuccessRouteImport } from './routes/_checkout/checkout/success'
import { Route as AuthenticatedEventsCreateRouteImport } from './routes/_authenticated/events/create'
import { Route as AuthenticatedEventsEditEventIdRouteImport } from './routes/_authenticated/events/edit.$eventId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceGalleryRoute = ExperienceGalleryRouteImport.update({
  id: '/experience-gallery',
  path: '/experience-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarEventsRoute = CalendarEventsRouteImport.update({
  id: '/calendar-events',
  path: '/calendar-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/_checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPaymentIdRoute = VerifyPaymentIdRouteImport.update({
  id: '/verify/$paymentId',
  path: '/verify/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTicketSalesRoute =
  AuthenticatedTicketSalesRouteImport.update({
    id: '/ticket-sales',
    path: '/ticket-sales',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemsRoute = AuthenticatedItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CheckoutCheckoutIndexRoute = CheckoutCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => CheckoutRoute,
} as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const CheckoutCheckoutSuccessRoute = CheckoutCheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const AuthenticatedEventsCreateRoute =
  AuthenticatedEventsCreateRouteImport.update({
    id: '/events/create',
    path: '/events/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsEditEventIdRoute =
  AuthenticatedEventsEditEventIdRouteImport.update({
    id: '/events/edit/$eventId',
    path: '/events/edit/$eventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/calendar-events': typeof CalendarEventsRoute
  '/experience-gallery': typeof ExperienceGalleryRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/items': typeof AuthenticatedItemsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/ticket-sales': typeof AuthenticatedTicketSalesRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/verify/$paymentId': typeof VerifyPaymentIdRoute
  '/events/create': typeof AuthenticatedEventsCreateRoute
  '/checkout/success': typeof CheckoutCheckoutSuccessRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/checkout/': typeof CheckoutCheckoutIndexRoute
  '/events/edit/$eventId': typeof AuthenticatedEventsEditEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/calendar-events': typeof CalendarEventsRoute
  '/experience-gallery': typeof ExperienceGalleryRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/items': typeof AuthenticatedItemsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/ticket-sales': typeof AuthenticatedTicketSalesRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/verify/$paymentId': typeof VerifyPaymentIdRoute
  '/events/create': typeof AuthenticatedEventsCreateRoute
  '/checkout/success': typeof CheckoutCheckoutSuccessRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/checkout': typeof CheckoutCheckoutIndexRoute
  '/events/edit/$eventId': typeof AuthenticatedEventsEditEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_checkout': typeof CheckoutRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/calendar-events': typeof CalendarEventsRoute
  '/experience-gallery': typeof ExperienceGalleryRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/items': typeof AuthenticatedItemsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/ticket-sales': typeof AuthenticatedTicketSalesRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/verify/$paymentId': typeof VerifyPaymentIdRoute
  '/_authenticated/events/create': typeof AuthenticatedEventsCreateRoute
  '/_checkout/checkout/success': typeof CheckoutCheckoutSuccessRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_checkout/checkout/': typeof CheckoutCheckoutIndexRoute
  '/_authenticated/events/edit/$eventId': typeof AuthenticatedEventsEditEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/calendar-events'
    | '/experience-gallery'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/items'
    | '/orders'
    | '/settings'
    | '/ticket-sales'
    | '/events/$eventId'
    | '/verify/$paymentId'
    | '/events/create'
    | '/checkout/success'
    | '/events/'
    | '/checkout/'
    | '/events/edit/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/calendar-events'
    | '/experience-gallery'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/items'
    | '/orders'
    | '/settings'
    | '/ticket-sales'
    | '/events/$eventId'
    | '/verify/$paymentId'
    | '/events/create'
    | '/checkout/success'
    | '/events'
    | '/checkout'
    | '/events/edit/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_checkout'
    | '/about-us'
    | '/calendar-events'
    | '/experience-gallery'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/items'
    | '/_authenticated/orders'
    | '/_authenticated/settings'
    | '/_authenticated/ticket-sales'
    | '/events/$eventId'
    | '/verify/$paymentId'
    | '/_authenticated/events/create'
    | '/_checkout/checkout/success'
    | '/_authenticated/events/'
    | '/_checkout/checkout/'
    | '/_authenticated/events/edit/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  CalendarEventsRoute: typeof CalendarEventsRoute
  ExperienceGalleryRoute: typeof ExperienceGalleryRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  VerifyPaymentIdRoute: typeof VerifyPaymentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience-gallery': {
      id: '/experience-gallery'
      path: '/experience-gallery'
      fullPath: '/experience-gallery'
      preLoaderRoute: typeof ExperienceGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar-events': {
      id: '/calendar-events'
      path: '/calendar-events'
      fullPath: '/calendar-events'
      preLoaderRoute: typeof CalendarEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_checkout': {
      id: '/_checkout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$paymentId': {
      id: '/verify/$paymentId'
      path: '/verify/$paymentId'
      fullPath: '/verify/$paymentId'
      preLoaderRoute: typeof VerifyPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ticket-sales': {
      id: '/_authenticated/ticket-sales'
      path: '/ticket-sales'
      fullPath: '/ticket-sales'
      preLoaderRoute: typeof AuthenticatedTicketSalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items': {
      id: '/_authenticated/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedItemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_checkout/checkout/': {
      id: '/_checkout/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutCheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_checkout/checkout/success': {
      id: '/_checkout/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutCheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/_authenticated/events/create': {
      id: '/_authenticated/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof AuthenticatedEventsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/edit/$eventId': {
      id: '/_authenticated/events/edit/$eventId'
      path: '/events/edit/$eventId'
      fullPath: '/events/edit/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEditEventIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedItemsRoute: typeof AuthenticatedItemsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTicketSalesRoute: typeof AuthenticatedTicketSalesRoute
  AuthenticatedEventsCreateRoute: typeof AuthenticatedEventsCreateRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedEventsEditEventIdRoute: typeof AuthenticatedEventsEditEventIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedItemsRoute: AuthenticatedItemsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTicketSalesRoute: AuthenticatedTicketSalesRoute,
  AuthenticatedEventsCreateRoute: AuthenticatedEventsCreateRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedEventsEditEventIdRoute: AuthenticatedEventsEditEventIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CheckoutRouteChildren {
  CheckoutCheckoutSuccessRoute: typeof CheckoutCheckoutSuccessRoute
  CheckoutCheckoutIndexRoute: typeof CheckoutCheckoutIndexRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutCheckoutSuccessRoute: CheckoutCheckoutSuccessRoute,
  CheckoutCheckoutIndexRoute: CheckoutCheckoutIndexRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  CalendarEventsRoute: CalendarEventsRoute,
  ExperienceGalleryRoute: ExperienceGalleryRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  VerifyPaymentIdRoute: VerifyPaymentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
