// This file is auto-generated by @hey-api/openapi-ts

export const Body_events_create_eventSchema = {
    properties: {
        event_data: {
            type: 'string',
            title: 'Event Data',
            description: 'Event JSON data'
        },
        flyer: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Flyer',
            description: 'Event flyer image (jpg, jpeg, png, max 4MB)'
        },
        gallery_images: {
            items: {
                type: 'string',
                format: 'binary'
            },
            type: 'array',
            title: 'Gallery Images',
            description: 'Gallery images (jpg, jpeg, png, max 4MB each, max 5 images)',
            default: []
        }
    },
    type: 'object',
    required: ['event_data'],
    title: 'Body_events-create_event'
} as const;

export const Body_events_update_eventSchema = {
    properties: {
        event_data: {
            type: 'string',
            title: 'Event Data',
            description: 'Event update JSON data'
        },
        flyer: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Flyer',
            description: 'New flyer image (jpg, jpeg, png, max 4MB)'
        },
        gallery_images: {
            items: {
                type: 'string',
                format: 'binary'
            },
            type: 'array',
            title: 'Gallery Images',
            description: 'New gallery images to add (jpg, jpeg, png, max 4MB each)',
            default: []
        }
    },
    type: 'object',
    required: ['event_data'],
    title: 'Body_events-update_event'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BookmarkStatusSchema = {
    properties: {
        is_bookmarked: {
            type: 'boolean',
            title: 'Is Bookmarked'
        }
    },
    type: 'object',
    required: ['is_bookmarked'],
    title: 'BookmarkStatus'
} as const;

export const BookmarkedEventsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/EventPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BookmarkedEventsPublic'
} as const;

export const CheckoutItemSchema = {
    properties: {
        ticket_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ticket Id'
        },
        quantity: {
            type: 'integer',
            maximum: 100,
            minimum: 1,
            title: 'Quantity'
        }
    },
    type: 'object',
    required: ['ticket_id', 'quantity'],
    title: 'CheckoutItem',
    description: 'Single item in checkout request.'
} as const;

export const CreateCheckoutRequestSchema = {
    properties: {
        event_id: {
            type: 'string',
            format: 'uuid',
            title: 'Event Id'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/CheckoutItem'
            },
            type: 'array',
            maxItems: 10,
            title: 'Items'
        },
        guest_info: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/GuestInfo'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['event_id', 'items'],
    title: 'CreateCheckoutRequest',
    description: 'Request to create a Stripe checkout session.'
} as const;

export const CreateCheckoutResponseSchema = {
    properties: {
        checkout_url: {
            type: 'string',
            title: 'Checkout Url'
        },
        session_id: {
            type: 'string',
            title: 'Session Id'
        },
        payment_id: {
            type: 'string',
            format: 'uuid',
            title: 'Payment Id'
        }
    },
    type: 'object',
    required: ['checkout_url', 'session_id', 'payment_id'],
    title: 'CreateCheckoutResponse',
    description: 'Response with Stripe checkout URL.'
} as const;

export const CustomerTypeSchema = {
    type: 'string',
    enum: ['guest', 'registered'],
    title: 'CustomerType'
} as const;

export const EventDropdownItemSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        }
    },
    type: 'object',
    required: ['id', 'title'],
    title: 'EventDropdownItem',
    description: 'Lightweight event item for dropdowns.'
} as const;

export const EventDropdownResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/EventDropdownItem'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        has_more: {
            type: 'boolean',
            title: 'Has More'
        }
    },
    type: 'object',
    required: ['data', 'count', 'has_more'],
    title: 'EventDropdownResponse',
    description: 'Response for events dropdown with pagination.'
} as const;

export const EventImagePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        event_id: {
            type: 'string',
            format: 'uuid',
            title: 'Event Id'
        },
        image_url: {
            type: 'string',
            title: 'Image Url'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'event_id', 'image_url', 'display_order', 'created_at'],
    title: 'EventImagePublic',
    description: 'API response schema for event gallery images.'
} as const;

export const EventPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        short_summary: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Short Summary'
        },
        start_datetime: {
            type: 'string',
            format: 'date-time',
            title: 'Start Datetime'
        },
        end_datetime: {
            type: 'string',
            format: 'date-time',
            title: 'End Datetime'
        },
        timezone: {
            type: 'string',
            maxLength: 50,
            title: 'Timezone',
            default: 'UTC'
        },
        recurring_series: {
            type: 'boolean',
            title: 'Recurring Series',
            default: false
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        location: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        venue_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Venue Name'
        },
        latitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latitude'
        },
        longitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Longitude'
        },
        show_on_explore: {
            type: 'boolean',
            title: 'Show On Explore',
            default: false
        },
        password_protected: {
            type: 'boolean',
            title: 'Password Protected',
            default: false
        },
        event_activity_social_feed: {
            type: 'boolean',
            title: 'Event Activity Social Feed',
            default: true
        },
        event_activity_updates_only: {
            type: 'boolean',
            title: 'Event Activity Updates Only',
            default: true
        },
        youtube_video_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Youtube Video Url'
        },
        flyer_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Flyer Url'
        },
        spotify_song_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Spotify Song Url'
        },
        title_font: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title Font'
        },
        accent_color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 7
                },
                {
                    type: 'null'
                }
            ],
            title: 'Accent Color'
        },
        is_featured: {
            type: 'boolean',
            title: 'Is Featured',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        status: {
            '$ref': '#/components/schemas/EventStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        tickets: {
            items: {
                '$ref': '#/components/schemas/TicketPublic'
            },
            type: 'array',
            title: 'Tickets',
            default: []
        },
        gallery_images: {
            items: {
                '$ref': '#/components/schemas/EventImagePublic'
            },
            type: 'array',
            title: 'Gallery Images',
            default: []
        }
    },
    type: 'object',
    required: ['title', 'start_datetime', 'end_datetime', 'id', 'status', 'created_at', 'updated_at', 'published_at'],
    title: 'EventPublic'
} as const;

export const EventSalesDetailSchema = {
    properties: {
        event_id: {
            type: 'string',
            format: 'uuid',
            title: 'Event Id'
        },
        event_title: {
            type: 'string',
            title: 'Event Title'
        },
        total_revenue: {
            type: 'integer',
            title: 'Total Revenue'
        },
        total_tickets_sold: {
            type: 'integer',
            title: 'Total Tickets Sold'
        },
        registered_user_count: {
            type: 'integer',
            title: 'Registered User Count'
        },
        guest_user_count: {
            type: 'integer',
            title: 'Guest User Count'
        },
        ticket_breakdown: {
            items: {
                '$ref': '#/components/schemas/TicketTypeSales'
            },
            type: 'array',
            title: 'Ticket Breakdown'
        },
        recent_sales: {
            items: {
                '$ref': '#/components/schemas/TicketSaleRecord'
            },
            type: 'array',
            title: 'Recent Sales'
        }
    },
    type: 'object',
    required: ['event_id', 'event_title', 'total_revenue', 'total_tickets_sold', 'registered_user_count', 'guest_user_count', 'ticket_breakdown', 'recent_sales'],
    title: 'EventSalesDetail',
    description: 'Detailed sales for a specific event.'
} as const;

export const EventStatsResponseSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        published: {
            type: 'integer',
            title: 'Published'
        },
        draft: {
            type: 'integer',
            title: 'Draft'
        },
        cancelled: {
            type: 'integer',
            title: 'Cancelled'
        },
        completed: {
            type: 'integer',
            title: 'Completed'
        }
    },
    type: 'object',
    required: ['total', 'published', 'draft', 'cancelled', 'completed'],
    title: 'EventStatsResponse',
    description: 'Statistics for events by status.'
} as const;

export const EventStatusSchema = {
    type: 'string',
    enum: ['draft', 'published', 'cancelled', 'completed'],
    title: 'EventStatus'
} as const;

export const EventsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/EventPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'EventsPublic'
} as const;

export const GuestInfoSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'GuestInfo',
    description: 'Guest customer information for checkout.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PaymentStatusSchema = {
    type: 'string',
    enum: ['pending', 'completed', 'failed', 'expired'],
    title: 'PaymentStatus'
} as const;

export const PaymentStatusResponseSchema = {
    properties: {
        payment_id: {
            type: 'string',
            format: 'uuid',
            title: 'Payment Id'
        },
        status: {
            '$ref': '#/components/schemas/PaymentStatus'
        },
        total_amount: {
            type: 'integer',
            title: 'Total Amount'
        },
        currency: {
            type: 'string',
            title: 'Currency'
        },
        paid_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paid At'
        },
        ticket_info: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ticket Info'
        },
        customer_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Name'
        },
        customer_email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Email'
        },
        event_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Event Id'
        }
    },
    type: 'object',
    required: ['payment_id', 'status', 'total_amount', 'currency', 'paid_at'],
    title: 'PaymentStatusResponse',
    description: 'Response for payment status check.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const StripePaymentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        event_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Event Id'
        },
        customer_type: {
            '$ref': '#/components/schemas/CustomerType'
        },
        ticket_info: {
            additionalProperties: true,
            type: 'object',
            title: 'Ticket Info'
        },
        total_amount: {
            type: 'integer',
            title: 'Total Amount'
        },
        currency: {
            type: 'string',
            title: 'Currency'
        },
        status: {
            '$ref': '#/components/schemas/PaymentStatus'
        },
        customer_email: {
            type: 'string',
            title: 'Customer Email'
        },
        customer_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Name'
        },
        customer_phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Phone'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        paid_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paid At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'event_id', 'customer_type', 'ticket_info', 'total_amount', 'currency', 'status', 'customer_email', 'customer_name', 'customer_phone', 'created_at', 'paid_at'],
    title: 'StripePaymentPublic',
    description: 'Public schema for stripe payment.'
} as const;

export const StripePaymentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/StripePaymentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'StripePaymentsPublic',
    description: 'Response schema for list of payments.'
} as const;

export const TicketPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        event_id: {
            type: 'string',
            format: 'uuid',
            title: 'Event Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price_amount: {
            type: 'integer',
            title: 'Price Amount'
        },
        price_currency: {
            type: 'string',
            title: 'Price Currency'
        },
        gross_price: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gross Price'
        },
        display_price: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Price'
        },
        quantity_total: {
            type: 'integer',
            title: 'Quantity Total'
        },
        quantity_sold: {
            type: 'integer',
            title: 'Quantity Sold'
        },
        is_unlimited: {
            type: 'boolean',
            title: 'Is Unlimited'
        },
        sale_start: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sale Start'
        },
        sale_end: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sale End'
        },
        validity_start: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Validity Start'
        },
        validity_end: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Validity End'
        },
        min_per_order: {
            type: 'integer',
            title: 'Min Per Order'
        },
        max_per_order: {
            type: 'integer',
            title: 'Max Per Order'
        },
        sell_in_bundles: {
            type: 'boolean',
            title: 'Sell In Bundles'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'event_id', 'name', 'description', 'price_amount', 'price_currency', 'gross_price', 'display_price', 'quantity_total', 'quantity_sold', 'is_unlimited', 'sale_start', 'sale_end', 'validity_start', 'validity_end', 'min_per_order', 'max_per_order', 'sell_in_bundles', 'created_at', 'updated_at'],
    title: 'TicketPublic'
} as const;

export const TicketSaleItemSchema = {
    properties: {
        ticket_id: {
            type: 'string',
            title: 'Ticket Id'
        },
        ticket_name: {
            type: 'string',
            title: 'Ticket Name'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        },
        unit_price: {
            type: 'integer',
            title: 'Unit Price'
        },
        total_price: {
            type: 'integer',
            title: 'Total Price'
        }
    },
    type: 'object',
    required: ['ticket_id', 'ticket_name', 'quantity', 'unit_price', 'total_price'],
    title: 'TicketSaleItem',
    description: 'Individual ticket sale in a payment.'
} as const;

export const TicketSaleRecordSchema = {
    properties: {
        payment_id: {
            type: 'string',
            format: 'uuid',
            title: 'Payment Id'
        },
        event_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Event Id'
        },
        event_title: {
            type: 'string',
            title: 'Event Title'
        },
        customer_type: {
            '$ref': '#/components/schemas/CustomerType'
        },
        customer_email: {
            type: 'string',
            title: 'Customer Email'
        },
        customer_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Name'
        },
        customer_phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Phone'
        },
        ticket_items: {
            items: {
                '$ref': '#/components/schemas/TicketSaleItem'
            },
            type: 'array',
            title: 'Ticket Items'
        },
        total_amount: {
            type: 'integer',
            title: 'Total Amount'
        },
        currency: {
            type: 'string',
            title: 'Currency'
        },
        status: {
            '$ref': '#/components/schemas/PaymentStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        paid_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paid At'
        }
    },
    type: 'object',
    required: ['payment_id', 'event_id', 'event_title', 'customer_type', 'customer_email', 'customer_name', 'customer_phone', 'ticket_items', 'total_amount', 'currency', 'status', 'created_at', 'paid_at'],
    title: 'TicketSaleRecord',
    description: 'Single ticket sale record for the admin view.'
} as const;

export const TicketSalesResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TicketSaleRecord'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        stats: {
            '$ref': '#/components/schemas/TicketSalesStats'
        }
    },
    type: 'object',
    required: ['data', 'count', 'stats'],
    title: 'TicketSalesResponse',
    description: 'Response for ticket sales list.'
} as const;

export const TicketSalesStatsSchema = {
    properties: {
        total_sales: {
            type: 'integer',
            title: 'Total Sales'
        },
        total_revenue: {
            type: 'integer',
            title: 'Total Revenue'
        },
        registered_user_sales: {
            type: 'integer',
            title: 'Registered User Sales'
        },
        guest_sales: {
            type: 'integer',
            title: 'Guest Sales'
        },
        pending_sales: {
            type: 'integer',
            title: 'Pending Sales'
        },
        tickets_sold: {
            type: 'integer',
            title: 'Tickets Sold'
        }
    },
    type: 'object',
    required: ['total_sales', 'total_revenue', 'registered_user_sales', 'guest_sales', 'pending_sales', 'tickets_sold'],
    title: 'TicketSalesStats',
    description: 'Statistics for ticket sales.'
} as const;

export const TicketTypeSalesSchema = {
    properties: {
        ticket_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ticket Id'
        },
        ticket_name: {
            type: 'string',
            title: 'Ticket Name'
        },
        quantity_sold: {
            type: 'integer',
            title: 'Quantity Sold'
        },
        revenue: {
            type: 'integer',
            title: 'Revenue'
        },
        price_amount: {
            type: 'integer',
            title: 'Price Amount'
        }
    },
    type: 'object',
    required: ['ticket_id', 'ticket_name', 'quantity_sold', 'revenue', 'price_amount'],
    title: 'TicketTypeSales',
    description: 'Sales breakdown by ticket type.'
} as const;

export const TicketVerificationResponseSchema = {
    properties: {
        is_valid: {
            type: 'boolean',
            title: 'Is Valid'
        },
        payment_id: {
            type: 'string',
            format: 'uuid',
            title: 'Payment Id'
        },
        status: {
            '$ref': '#/components/schemas/PaymentStatus'
        },
        event_title: {
            type: 'string',
            title: 'Event Title'
        },
        event_date: {
            type: 'string',
            format: 'date-time',
            title: 'Event Date'
        },
        customer_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Name'
        },
        ticket_items: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Ticket Items',
            default: []
        },
        total_amount: {
            type: 'integer',
            title: 'Total Amount'
        },
        currency: {
            type: 'string',
            title: 'Currency'
        },
        paid_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paid At'
        },
        verified_at: {
            type: 'string',
            format: 'date-time',
            title: 'Verified At'
        }
    },
    type: 'object',
    required: ['is_valid', 'payment_id', 'status', 'event_title', 'event_date', 'total_amount', 'currency', 'verified_at'],
    title: 'TicketVerificationResponse',
    description: 'Response for public ticket verification.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;