// This file is auto-generated by @hey-api/openapi-ts

export type Body_events_create_event = {
    /**
     * Event JSON data
     */
    event_data: string;
    /**
     * Event flyer image (jpg, jpeg, png, max 4MB)
     */
    flyer?: ((Blob | File) | null);
    /**
     * Gallery images (jpg, jpeg, png, max 4MB each, max 5 images)
     */
    gallery_images?: Array<((Blob | File))>;
};

export type Body_events_update_event = {
    /**
     * Event update JSON data
     */
    event_data: string;
    /**
     * New flyer image (jpg, jpeg, png, max 4MB)
     */
    flyer?: ((Blob | File) | null);
    /**
     * New gallery images to add (jpg, jpeg, png, max 4MB each)
     */
    gallery_images?: Array<((Blob | File))>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BookmarkedEventsPublic = {
    data: Array<EventPublic>;
    count: number;
};

export type BookmarkStatus = {
    is_bookmarked: boolean;
};

/**
 * Single item in checkout request.
 */
export type CheckoutItem = {
    ticket_id: string;
    quantity: number;
};

/**
 * Request to create a Stripe checkout session.
 */
export type CreateCheckoutRequest = {
    event_id: string;
    items: Array<CheckoutItem>;
    guest_info?: (GuestInfo | null);
};

/**
 * Response with Stripe checkout URL.
 */
export type CreateCheckoutResponse = {
    checkout_url: string;
    session_id: string;
    payment_id: string;
};

export type CustomerType = 'guest' | 'registered';

/**
 * Lightweight event item for dropdowns.
 */
export type EventDropdownItem = {
    id: string;
    title: string;
};

/**
 * Response for events dropdown with pagination.
 */
export type EventDropdownResponse = {
    data: Array<EventDropdownItem>;
    count: number;
    has_more: boolean;
};

/**
 * API response schema for event gallery images.
 */
export type EventImagePublic = {
    id: string;
    event_id: string;
    image_url: string;
    display_order: number;
    created_at: string;
};

export type EventPublic = {
    title: string;
    short_summary?: (string | null);
    start_datetime: string;
    end_datetime: string;
    timezone?: string;
    recurring_series?: boolean;
    description?: (string | null);
    location?: (string | null);
    venue_name?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
    show_on_explore?: boolean;
    password_protected?: boolean;
    event_activity_social_feed?: boolean;
    event_activity_updates_only?: boolean;
    youtube_video_url?: (string | null);
    flyer_url?: (string | null);
    spotify_song_url?: (string | null);
    title_font?: (string | null);
    accent_color?: (string | null);
    is_featured?: boolean;
    id: string;
    status: EventStatus;
    created_at: string;
    updated_at: string;
    published_at: (string | null);
    tickets?: Array<TicketPublic>;
    gallery_images?: Array<EventImagePublic>;
};

/**
 * Detailed sales for a specific event.
 */
export type EventSalesDetail = {
    event_id: string;
    event_title: string;
    total_revenue: number;
    total_tickets_sold: number;
    registered_user_count: number;
    guest_user_count: number;
    ticket_breakdown: Array<TicketTypeSales>;
    recent_sales: Array<TicketSaleRecord>;
};

export type EventsPublic = {
    data: Array<EventPublic>;
    count: number;
};

/**
 * Statistics for events by status.
 */
export type EventStatsResponse = {
    total: number;
    published: number;
    draft: number;
    cancelled: number;
    completed: number;
};

export type EventStatus = 'draft' | 'published' | 'cancelled' | 'completed';

/**
 * Guest customer information for checkout.
 */
export type GuestInfo = {
    email: string;
    name?: (string | null);
    phone?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PaymentStatus = 'pending' | 'completed' | 'failed' | 'expired';

/**
 * Response for payment status check.
 */
export type PaymentStatusResponse = {
    payment_id: string;
    status: PaymentStatus;
    total_amount: number;
    currency: string;
    paid_at: (string | null);
    ticket_info?: ({
    [key: string]: unknown;
} | null);
    customer_name?: (string | null);
    customer_email?: (string | null);
    event_id?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Public schema for stripe payment.
 */
export type StripePaymentPublic = {
    id: string;
    user_id: (string | null);
    event_id: (string | null);
    customer_type: CustomerType;
    ticket_info: {
        [key: string]: unknown;
    };
    total_amount: number;
    currency: string;
    status: PaymentStatus;
    customer_email: string;
    customer_name: (string | null);
    customer_phone: (string | null);
    created_at: string;
    paid_at: (string | null);
};

/**
 * Response schema for list of payments.
 */
export type StripePaymentsPublic = {
    data: Array<StripePaymentPublic>;
    count: number;
};

export type TicketPublic = {
    id: string;
    event_id: string;
    name: string;
    description: (string | null);
    price_amount: number;
    price_currency: string;
    gross_price: (number | null);
    display_price: (number | null);
    quantity_total: number;
    quantity_sold: number;
    is_unlimited: boolean;
    sale_start: (string | null);
    sale_end: (string | null);
    validity_start: (string | null);
    validity_end: (string | null);
    min_per_order: number;
    max_per_order: number;
    sell_in_bundles: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * Individual ticket sale in a payment.
 */
export type TicketSaleItem = {
    ticket_id: string;
    ticket_name: string;
    quantity: number;
    unit_price: number;
    total_price: number;
};

/**
 * Single ticket sale record for the admin view.
 */
export type TicketSaleRecord = {
    payment_id: string;
    event_id: (string | null);
    event_title: string;
    customer_type: CustomerType;
    customer_email: string;
    customer_name: (string | null);
    customer_phone: (string | null);
    ticket_items: Array<TicketSaleItem>;
    total_amount: number;
    currency: string;
    status: PaymentStatus;
    created_at: string;
    paid_at: (string | null);
};

/**
 * Response for ticket sales list.
 */
export type TicketSalesResponse = {
    data: Array<TicketSaleRecord>;
    count: number;
    stats: TicketSalesStats;
};

/**
 * Statistics for ticket sales.
 */
export type TicketSalesStats = {
    total_sales: number;
    total_revenue: number;
    registered_user_sales: number;
    guest_sales: number;
    pending_sales: number;
    tickets_sold: number;
};

/**
 * Sales breakdown by ticket type.
 */
export type TicketTypeSales = {
    ticket_id: string;
    ticket_name: string;
    quantity_sold: number;
    revenue: number;
    price_amount: number;
};

/**
 * Response for public ticket verification.
 */
export type TicketVerificationResponse = {
    is_valid: boolean;
    payment_id: string;
    status: PaymentStatus;
    event_title: string;
    event_date: string;
    customer_name?: (string | null);
    ticket_items?: Array<{
        [key: string]: unknown;
    }>;
    total_amount: number;
    currency: string;
    paid_at?: (string | null);
    verified_at: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CheckoutCreateCheckoutSessionData = {
    requestBody: CreateCheckoutRequest;
};

export type CheckoutCreateCheckoutSessionResponse = (CreateCheckoutResponse);

export type CheckoutGetPaymentStatusData = {
    sessionId: string;
};

export type CheckoutGetPaymentStatusResponse = (PaymentStatusResponse);

export type CheckoutGetPaymentByIdData = {
    paymentId: string;
};

export type CheckoutGetPaymentByIdResponse = (PaymentStatusResponse);

export type CheckoutGetMyOrdersData = {
    limit?: number;
    skip?: number;
};

export type CheckoutGetMyOrdersResponse = (StripePaymentsPublic);

export type CheckoutVerifyTicketData = {
    paymentId: string;
};

export type CheckoutVerifyTicketResponse = (TicketVerificationResponse);

export type EventsGetEventsDropdownData = {
    limit?: number;
    /**
     * Search by event title
     */
    search?: (string | null);
    skip?: number;
};

export type EventsGetEventsDropdownResponse = (EventDropdownResponse);

export type EventsReadEventsData = {
    limit?: number;
    skip?: number;
    status?: (EventStatus | null);
};

export type EventsReadEventsResponse = (EventsPublic);

export type EventsCreateEventData = {
    formData: Body_events_create_event;
};

export type EventsCreateEventResponse = (EventPublic);

export type EventsReadMyEventsData = {
    limit?: number;
    skip?: number;
    status?: (EventStatus | null);
};

export type EventsReadMyEventsResponse = (EventsPublic);

export type EventsGetMyEventsStatsResponse = (EventStatsResponse);

export type EventsReadEventData = {
    eventId: string;
};

export type EventsReadEventResponse = (EventPublic);

export type EventsUpdateEventData = {
    eventId: string;
    formData: Body_events_update_event;
};

export type EventsUpdateEventResponse = (EventPublic);

export type EventsDeleteEventData = {
    eventId: string;
};

export type EventsDeleteEventResponse = (Message);

export type EventsCheckBookmarkData = {
    eventId: string;
};

export type EventsCheckBookmarkResponse = (BookmarkStatus);

export type EventsAddBookmarkData = {
    eventId: string;
};

export type EventsAddBookmarkResponse = (BookmarkStatus);

export type EventsRemoveBookmarkData = {
    eventId: string;
};

export type EventsRemoveBookmarkResponse = (BookmarkStatus);

export type EventsDeleteGalleryImageEndpointData = {
    eventId: string;
    imageId: string;
};

export type EventsDeleteGalleryImageEndpointResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TicketSalesGetTicketSalesData = {
    /**
     * Filter by customer type
     */
    customerType?: (CustomerType | null);
    /**
     * Filter by event
     */
    eventId?: (string | null);
    limit?: number;
    /**
     * Search by email, name, or event title
     */
    search?: (string | null);
    skip?: number;
    /**
     * Filter by status
     */
    status?: (PaymentStatus | null);
};

export type TicketSalesGetTicketSalesResponse = (TicketSalesResponse);

export type TicketSalesGetEventSalesDetailData = {
    eventId: string;
};

export type TicketSalesGetEventSalesDetailResponse = (EventSalesDetail);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserBookmarksData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUserBookmarksResponse = (BookmarkedEventsPublic);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WebhooksStripeWebhookData = {
    stripeSignature: string;
};

export type WebhooksStripeWebhookResponse = ({
    [key: string]: unknown;
});